DROP DATABASE IF EXISTS MAIRIE_DB;

CREATE DATABASE MAIRIE_DB;

USE MAIRIE_DB;

CREATE TABLE CITOYEN (
    CODECITOYEN INT NOT NULL AUTO_INCREMENT,
    NOM TEXT,
    POSTNOM TEXT,
    PRENOM TEXT,
    GENRE CHAR(1),
    DATEDENAISSANCE DATE,
    LIEUDENAISSANCE TEXT,
    ADRESSE TEXT,
    CONTACT TEXT,
    EMAIL TEXT,
    PERE TEXT,
    MERE TEXT,
    PARTENAIRE TEXT,
    ENFANT TEXT,
    ETATCIVIL TEXT,
    PROFESSION TEXT,
    CHEFFERIE TEXT,
    TERRITOIRE TEXT,
    PROVINCE TEXT,
    NATIONALITE TEXT,
    IDCARTE TEXT,
    VISIBLE INT,
    AUTEUR TEXT,
    CONSTRAINT PK_DECLARANT PRIMARY KEY (CODECITOYEN)
);

CREATE TABLE DOCUMENT (
    CODEDOCUMENT INT NOT NULL AUTO_INCREMENT,
    DESIGNATION TEXT,
    PRIX FLOAT,
    DESCRIPTION TEXT,
    VISIBLE INT,
    AUTEUR TEXT,
    CONSTRAINT PK_DOC PRIMARY KEY(CODEDOCUMENT)
);

CREATE TABLE COMMANDE (
    CODECOMMANDE INT NOT NULL AUTO_INCREMENT,
    DECLARANT INT,
    DOCUMENT INT,
    STATUT INT,
    DDATE DATETIME CURRENT_TIMESTAMP,
    VISIBLE INT,
    AUTEUR TEXT,
    CONSTRAINT PK_COMMANDE PRIMARY KEY(CODECOMMANDE),
    CONSTRAINT FK_DECLARANT FOREIGN KEY(DECLARANT) REFERENCES CITOYEN(CODECITOYEN),
    CONSTRAINT FK_DOCUMENT FOREIGN KEY(DOCUMENT) REFERENCES DOCUMENT(CODEDOCUMENT)
);

CREATE TABLE PAYEMENT (
    CODEPAYEMENT INT NOT NULL AUTO_INCREMENT,
    COMMANDE INT,
    MONTANT FLOAT,
    DDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    VISIBLE INT,
    STATUT INT,
    AUTEUR TEXT,
    CONSTRAINT PK_PAYEMENT PRIMARY KEY (CODEPAYEMENT),
    CONSTRAINT FK_COMMANDE FOREIGN KEY (COMMANDE) REFERENCES COMMANDE(CODECOMMANDE)
);

CREATE TABLE LIVRAISON (
    CODELIVRAISON INT NOT NULL AUTO_INCREMENT,
    PAYEMENT INT,
    DDATE DATETIME,
    VISIBLE INT,
    AUTEUR TEXT,
    CONSTRAINT PK_LIVRAISON PRIMARY KEY (CODELIVRAISON),
    CONSTRAINT FK_PAYEMENT FOREIGN KEY (PAYEMENT) REFERENCES PAYEMENT(CODEPAYEMENT)
);

CREATE TABLE SERVICE (
    CODESERVICE INT NOT NULL AUTO_INCREMENT,
    DESIGNATION TEXT,
    EMAIL TEXT,
    VISIBLE INT,
    AUTEUR TEXT,
    CONSTRAINT PK_FONCTION PRIMARY KEY (CODESERVICE)
);

CREATE TABLE UTILISATEUR (
    CODEUTILISATEUR INT NOT NULL AUTO_INCREMENT,
    NOM TEXT,
    POSTNOM TEXT,
    PRENOM TEXT,
    FONCTION INT,
    VISIBLE INT,
    PHOTO TEXT,
    AUTEUR TEXT,
    CONSTRAINT PK_UTILISATEUR PRIMARY KEY (CODEUTILISATEUR),
    CONSTRAINT FK_FONCTION FOREIGN (FONCTION) REFERENCES SERVICE(CODESERVICE)
);

CREATE TABLE COMPTE (
    CODECOMPTE INT NOT NULL AUTO_INCREMENT,
    UTILISATEUR INT,
    NOMUTILISATEUR TEXT,
    MOTDEPASSE TEXT,
    VISIBLE INT,
    CONSTRAINT PK_COMPTE PRIMARY KEY (CODECOMPTE),
    CONSTRAINT FK_UTILISATEUR FOREIGN KEY (UTILISATEUR) REFERENCES UTILISATEUR(CODEUTILISATEUR)
);

INSERT INTO `SERVICE` (
    `CODESERVICE`,
    `DESIGNATION`,
    `EMAIL`,
    `VISIBLE`,
    `AUTEUR`
) VALUES (
    NULL,
    'Administrateur',
    NULL,
    '1',
    'Administrateur'
);

INSERT INTO `UTILISATEUR` (
    `CODEUTILISATEUR`,
    `NOM`,
    `POSTNOM`,
    `PRENOM`,
    `FONCTION`,
    `VISIBLE`,
    `AUTEUR`
) VALUES (
    NULL,
    'admin',
    'admin',
    'admin',
    '1',
    '1',
    'Administrateur'
);